name: Generate Posts

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:  # Allows manual triggering

# Add permissions for creating issues
permissions:
  issues: write
  contents: read

jobs:
  generate-posts:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Type check
      run: npm run type-check || exit 1
    
    - name: Generate Posts
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      run: |
        npm run generate-post || {
          echo "Post generation failed with exit code $?"
          exit 1
        }
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Post Generation Failed',
            body: `The post generation workflow failed at ${new Date().toISOString()}\n\nPlease check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
          }); 